data:
  data_dir: /home/ljh/disk/dataset/EvRealHands
  dataset: EvHand
  eval_subject:
  - 1
  - 3
  flip: true
  fps: 15
  hand_type: right
  height: 260
  mano_key: manos
  smplx_path: /home/ljh/code/smplx_models/mano
  train_subject:
  - 0
  - 2
  - 4
  - 5
  - 6
  - 8
  - 9
  val_subject:
  - 7
  width: 346
exper:
  debug: false
  early_stop: false
  epochs: 40
  exper_name: train_semi
  gpus: 0
  mode: train
  output_dir: /home/ljh/code/Event3DHandPoseEstimation/exper/EvHand_semi
  patience: 10
  strategy: ddp
  supervision:
  - supervision
  - semi-supervision
log:
  aligned_mesh: false
  gt_show: false
  imshow: false
  inter_debug: false
  render_background: true
  show_mesh: false
  verbose: false
loss:
  basic:
    blur_radius: 3.0e-05
  cm:
    N_inter: 4
    weight: -3.0
  edge:
    dist_bias: 4
    factor: 0.3
    iwe_percentage: 0.001
    motion: true
    motion_bias: 4
    orient: true
    orient_bias: 0.2
    search_window: 12
    weight: 0.05
  flow:
    weight: 0.0
  joint_3d:
    weight: 1000.0
  mano:
    hand_pose_weight: 5.0
    rot_weight: 10.0
    shape_weight: 0.25
    trans_weight: 2000.0
    weight: 0.1
  smooth:
    hand_pose_weight: 1.0
    margin: 0.5
    rot_weight: 0.1
    shape_weight: 0.2
    soften: true
    soften_rate: 1.0
    trans_weight: 1000.0
    weight: 0.2
  supervision:
    weight: 1.0
method:
  block: BasicBlock
  encoder_fusion:
    channel_sizes:
    - 3
    - 4
    - 6
    - 3
    residual_norm: BN
  event_encoder:
    base_num_channels: 64
    channel_sizes: []
    num_bins: 1
    residual_norm: BN
    usage: true
  flow:
    base_num_channels: 32
    fixed: true
    kernel_size: 3
    last_for_output: true
    model_path: 
    num_bins: 5
    num_encoders: 4
    num_residual_blocks: 2
    train: false
    usage: true
  loop_supervision: 1
  model_path: 
  name: EvHands
  optimizers:
    infer_encoder:
      lr: 5.0e-05
      name: Adam
      weight_decay: 0.0001
  predictor:
    layer_dims:
    - 128
    - 61
    mean:
    - 0.15
    - 0.0
    - 0.5
    scale:
    - 0.3
    - 0.3
    - 0.3
  seq_model:
    annot_len: 3
    model: ConvGRU
    num_layers: 1
    seq_len: 12
  supervision_type: all_loss
preprocess:
  acquire_aps: false
  activity_filter: false
  activity_filter_N_thre: 4
  activity_filter_delta_t: 8000
  annot_use_rate: 1.0
  augment:
    depth_range:
    - 0.7
    - 1.3
    gaussian_mean: 0.0
    gaussian_sigma: 0.05
    rotate_var: 0.3
    salt_pepper: 0.001
    scale_var: 0.1
    trans_range_x:
    - -0.3
    - 0.3
    trans_range_y:
    - -0.3
    - 0.3
    trans_var: 0.1
  batch_size: 32
  bbox:
    joints_to_bbox_rate: 2.0
    resize: true
    shift_var: 0.15
    size: 128
    usage: true
  height: 260
  interpolate: true
  max_window_time: 100000.0
  min_window_time: 10000.0
  num_events: 10000
  num_workers: 8
  repre: LNES
  same_time_window: 66666.0
  test_fps: 15
  test_window_augmentation: false
  update_period: 1
  width: 346
  window_stride: 1
  window_time_var: 50000.0
